version: '3.8'

services:
  # Servicio para el frontend (React)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80" # Mapea el puerto 80 del contenedor al puerto 8080 del host
    networks:
      - app-network

  # Servicio para el backend (PHP)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:80" # Mapea el puerto 80 del contenedor al puerto 8000 del host
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
